### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by pdeziel** [rotationalio/pyensign#69]
**Describe the solution you'd like**
In `ensign.py` we would like to use type annotations in the function definitions so that it's clear what expected types the parameters should have.

**Comment by Dv04** [comment]
Can I get assigned to this issue? I will submit the PR on October 1st

I just have some questions, which of the functions need type annotation, or do all of the functions need them? 
Also, almost all docstrings, if not all, contain the type annotations so should I just make the annotations as such?

**Comment by pdeziel** [comment]
> @pdeziel Can I get assigned to this issue? I will submit the PR on October 1st
> 
> I just have some questions, which of the functions need type annotation, or do all of the functions need them? Also, almost all docstrings, if not all, contain the type annotations so should I just make the annotations as such?

Absolutely, we would greatly appreciate it. I think for this issue we should add annotations to all of the `Ensign` class functions in `ensign.py` that are implemented, e.g. if the method raises `NotImplemented` then you don't need to annotate those. As you said you will probably just be able to infer the types from the docstrings.

I look forward to your contribution!

**Comment by Dv04** [comment]
Great, will update you as soon as done.
