### ISSUE TITLE
Add more detailed steps to create a Project and access the API Key in the docs

### ISSUE THREAD

**Issue by Mikerniker** [rotationalio/pyensign#72]
Hi, I recently watched the recent YouTube videos for Creating a Project, Topics, and accessing the API Key  and would like to request if I can add the details that were in those videos to create the written step-by-step process in either the Quickstart for the website or documentation as part of the Hacktoberfest? Some of the details that were in the video don't seem to appear in the Quickstart of the website and would like to help add those details it in the docs or website if possible. Thank you!

**Comment by pdeziel** [comment]
Hi @Mikerniker thanks for your feedback and I'm so glad you're willing to make the docs updates yourself! The developer docs are in one of our other repos so I've opened a parallel issue there: https://github.com/rotationalio/ensign/issues/756

The docs are a static generated site, so it would actually be pretty easy for you to open a PR there; it just involves installing hugo and editing a markdown file. If you're willing to do that, you can comment on the issue there and I can assign it to you. https://github.com/rotationalio/ensign/issues/756
